// src/lib/components/ArticleItem.svelte
<script lang="ts">
	import TagList from './TagList.svelte'
	import Time from './Time.svelte'
	import type { Article } from '$lib/data'

	export let article: Article
</script>

<a class="block transition-colors hover:text-accent {$$props.class ?? ''}" href={article.url}>
	<h4 class="font-heading text-2xl font-semibold">{article.title}</h4>
	<div class="flex items-center gap-2">
		<Time date={article.date} />
		<TagList tags={article.tags} />
	</div>

	<p class="text-sm">{article.description}</p>
</a>

// app/components/article-item.tsx
import clsx from 'clsx'
import { Link } from 'remix'
import type { Article } from '~/data/articles'
import { TagList } from './tag-list'
import { Time } from './time'

export interface ArticleItemProps {
  article: Article
  className?: string
}
export function ArticleItem({
  article: { url, date, tags, title, description, intro, image },
  className,
}: ArticleItemProps) {
  return (
    <Link className={clsx('block transition-colors hover:text-accent', className)} to={url}>
      <h4 className="text-2xl font-extrabold font-heading">{title}</h4>
      <div className="flex items-center gap-2">
        <Time date={date} />
        <TagList tags={tags} />
      </div>

      <p className="text-sm">{intro ?? description}</p>
    </Link>
  )
}
