// src/lib/components/Prose.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLAttributes } from 'svelte/elements'

  interface Props extends HTMLAttributes<HTMLDivElement> {
    children?: Snippet
  }
  let { class: className, children, ...props }: Props = $props()
</script>

<div
  {...props}
  class={[
    'prose container',
    'md:prose-lg lg:prose-xl flex-grow',
    'prose-headings:font-heading',
    'prose-a:text-accent-dark',
    className,
  ]}
>
  {@render children?.()}
</div>

// app/components/prose.tsx
import clsx from 'clsx'
import { ReactNode } from 'react'

export interface ProseProps {
  className?: string
  children: ReactNode
}
export function Prose({ className, children }: ProseProps) {
  return (
    <div
      className={clsx([
        'prose md:prose-lg lg:prose-xl',
        'prose-headings:font-heading',
        'prose-a:text-accent-dark',
        className,
      ])}
    >
      {children}
    </div>
  )
}
