// src/lib/components/Time.svelte
<script lang="ts">
  import { format, parseISO } from 'date-fns'

  interface Props {
    date: string
  }
  let { date }: Props = $props()

  let parsedDate = $derived(date && parseISO(String(date)))
  let dateFormatted = $derived(parsedDate && format(parsedDate, 'MMMM yyy'))
</script>

<time class="text-sm" dateTime={date}>
  {dateFormatted}
</time>

// app/components/time.tsx
import { format, parseISO } from 'date-fns'

export interface TimeProps {
  date: string
}
export function Time({ date }: TimeProps) {
  if (!date) {
    return null
  }
  const parsedDate = date && parseISO(String(date))
  const dateFormatted = parsedDate && format(parsedDate, 'MMMM yyy')

  return (
    <time className="text-sm" dateTime={date}>
      {dateFormatted}
    </time>
  )
}
