// src/lib/components/blocks/RandomImageBlock.svelte
<script lang="ts">
  import { randomValue } from '$lib/utils'
  import type { HTMLAttributes } from 'svelte/elements'

  interface Props extends HTMLAttributes<HTMLDivElement> {
    images: string[]
  }
  let { title, images, class: className, ...props }: Props = $props()

  let randomImage = $derived(randomValue(images))
</script>

<div
  class={[
    'not-prose w-prose-full header-offset-mobile lg:header-offset-desktop relative flex',
    'min-h-[50vh] items-end justify-center',
    className,
  ]}
  {...props}
>
  <img
    class="absolute h-full w-full object-cover"
    src={randomImage}
    alt={title ?? 'Hero Image'}
    width={2048}
    height={1024}
  />
  {#if title}
    <div class="z-10 my-8 flex flex-col items-center">
      <h1 class="heading-1 text-white">{title}</h1>
    </div>
  {/if}
</div>

// blocks/random-image.block.tsx
import clsx from 'clsx'
import Image, { StaticImageData } from 'next/image'
import { HTMLAttributes } from 'react'
import { useRandomValue } from '~/utils'

export interface RandomImageBlockProps extends HTMLAttributes<HTMLDivElement> {
  title?: string
  images: string[] | StaticImageData[]
}
export function RandomImageBlock({ title, images, className }: RandomImageBlockProps) {
  const randomImage: any = useRandomValue(images as any)
  return (
    <div
      className={clsx(
        // place under header, and make full width
        'not-prose w-prose-full header-offset-mobile lg:header-offset-desktop relative min-h-[50vh]',
        'flex items-end justify-center',
        className,
      )}
    >
      <Image
        className="absolute h-full w-full object-cover"
        src={randomImage}
        alt={title ?? 'Hero Image'}
        width={2048}
        height={1024}
        priority
      />
      {title && (
        <div className="z-10 my-8 flex flex-col items-center">
          <h1 className="heading-1 text-white">{title}</h1>
        </div>
      )}
    </div>
  )
}
