// app/blocks/colors-hero.block.tsx
import clsx from 'clsx'
import { useRandomColor } from '~/utils'

export interface GradientHeroBlockProps {
  title: string
}
export function ColorsHeroBlock({ title }: GradientHeroBlockProps) {
  const randomColor = useRandomColor()
  return (
    <div
      className={clsx([
        'no-prose relative header-offset-mobile lg:header-offset-desktop',
        'flex justify-center items-end min-h-[30vh]',
        'bg-no-repeat bg-cover',
      ])}
      style={{
        backgroundColor: randomColor,
        backgroundImage: `url(/backgrounds/light-glow.svg)`,
      }}
    >
      <h1 className="my-16 capitalize heading-1">{title}</h1>
    </div>
  )
}

// src/lib/components/blocks/ColorsHeroBlock.svelte
<script lang="ts">
	import { randomColor } from '$lib/utils'

	export let title: string

	const randomColorStr = randomColor()
</script>

<div
	class="
    no-prose header-offset-mobile lg:header-offset-desktop relative
    flex min-h-[30vh] items-end justify-center
    bg-cover bg-no-repeat
    {$$props.class ?? ''}
  "
	style:background-color={randomColorStr}
>
	<h1 class="heading-1 my-16 capitalize">{title}</h1>
</div>
<!-- style:background-image="url(/backgrounds/light-glow.svg)" -->
