// app/blocks/intro.block.tsx
import clsx from 'clsx'
import { Gradient } from '~/components/gradient'

export interface IntroBlockProps {}
export function IntroBlock({}: IntroBlockProps) {
  return (
    <Gradient className="relative header-offset-mobile lg:header-offset-desktop">
      <div className="container flex max-w-screen-xl grow">
        <div
          className={clsx(
            'min-h-[40vh]',
            // mobile
            'grow grid grid-flow-row place-items-center',
            // desktop
            'md:grid-flow-col md:auto-cols-fr',
          )}
        >
          <img
            className="block object-contain w-full h-auto max-w-xs m-8 rounded-full shadow-md"
            src="/images/leon-radley.jpg"
            alt="Picture of Leon Radley"
            width={320}
            height={320}
          />
          <div className="my-8">
            <h1 className="heading-1">Hello, I'm Leon 👋</h1>
            <p className="text-lg">I love tech, coding and everything web.</p>
            <p className="text-lg">
              Here you will find articles, labs and projects relating to web development, 3d and programming in general.
            </p>
          </div>
        </div>
      </div>
    </Gradient>
  )
}

// src/lib/components/blocks/IntroBlock.svelte
<script lang="ts">
  import Gradient from '../Gradient.svelte'
</script>

<Gradient class="header-offset-mobile lg:header-offset-desktop relative">
  <div class="relative container flex max-w-screen-xl grow">
    <div
      class={[
        'grid',
        'min-h-[40vh] grow grid-flow-row place-items-center',
        'md:auto-cols-fr md:grid-flow-col',
      ]}
    >
      <img
        class="m-8 block h-auto w-full max-w-xs rounded-full object-contain shadow-md"
        src="/images/leon-radley.jpg"
        alt="Leon Radley"
        width={320}
        height={320}
      />
      <div class="my-8">
        <h1 class="heading-1">Hello, I'm Leon 👋</h1>
        <p class="text-lg">I love tech, coding and everything web.</p>
        <p class="text-lg">
          Here you will find articles, labs and projects relating to web development, 3d and
          programming in general.
        </p>
      </div>
    </div>
  </div>
</Gradient>
