// app/blocks/random-image.block.tsx
import clsx from 'clsx'
import { HTMLAttributes } from 'react'
import { Image } from '~/components/Image'
import { useRandomValue } from '~/utils/useRandomValue'

export interface RandomImageBlockProps extends HTMLAttributes<HTMLDivElement> {
  title: string
  images: string[]
}
export function RandomImageBlock({ title, images, className }: RandomImageBlockProps) {
  const randomImage = images && images.length > 0 ? useRandomValue(images) : null
  return (
    <div
      className={clsx(
        // place under header, and make full width
        'not-prose relative w-prose-full min-h-[50vh] header-offset-mobile lg:header-offset-desktop',
        'flex justify-center items-end',
        className,
      )}
    >
      {randomImage && (
        <Image className="absolute object-cover w-full h-full" src={randomImage} width={2048} />
      )}
      <div className="z-10 flex flex-col items-center my-8">
        <h1 className="text-white heading-1">{title}</h1>
      </div>
    </div>
  )
}

// src/lib/components/blocks/RandomImageBlock.svelte
<script lang="ts">
  import { randomValue } from '$lib/utils'
  import type { HTMLAttributes } from 'svelte/elements'

  interface Props extends HTMLAttributes<HTMLDivElement> {
    images: string[]
  }
  let { title, images, class: className, ...props }: Props = $props()

  let randomImage = $derived(randomValue(images))
</script>

<div
  class={[
    'not-prose w-prose-full header-offset-mobile lg:header-offset-desktop relative flex',
    'min-h-[50vh] items-end justify-center',
    className,
  ]}
  {...props}
>
  <img
    class="absolute h-full w-full object-cover"
    src={randomImage}
    alt={title ?? 'Hero Image'}
    width={2048}
    height={1024}
  />
  {#if title}
    <div class="z-10 my-8 flex flex-col items-center">
      <h1 class="heading-1 text-white">{title}</h1>
    </div>
  {/if}
</div>
