// src/lib/components/ProjectCard.svelte
<script lang="ts">
	export let href: string
	export let image: {
		src: string
		width: number
		height: number
	}
	export let topic: string
	export let title: string
	export let description: string
</script>

<a class="block transition-colors hover:text-accent {$$props.class ?? ''}" {href}>
	{#if image}
		<img class="mb-2 block" alt="" {...image} />
	{/if}
	<div class="badge">{topic}</div>
	<h4 class="font-heading text-2xl font-bold">{title}</h4>
	<p class="text-sm">{description}</p>
</a>

// components/project-card.tsx
/* eslint-disable @next/next/no-img-element */
import clsx from 'clsx'
import Link from 'next/link'
import type { Project } from '~/data/projects'

export interface ProjectCardProps {
  article: Project
  className?: string
}
export function ProjectCard({
  article: { url, topic, title, intro, image },
  className,
}: ProjectCardProps) {
  return (
    <Link className={clsx('block transition-colors hover:text-accent', className)} href={url}>
      {image && <img className="mb-2 block" alt="" {...image} />}
      <div className="badge">{topic}</div>
      <h4 className="font-heading text-2xl font-bold">{title}</h4>
      <p className="text-sm">{intro}</p>
    </Link>
  )
}
