// src/lib/components/blocks/GradientHeroBlock.svelte
<script lang="ts">
	import Gradient from '../Gradient.svelte'

	export let title: string
</script>

<Gradient
	class="
    no-prose header-offset-mobile lg:header-offset-desktop relative
    flex min-h-[30vh] items-end justify-center
  "
>
	<h1 class="heading-1 my-16 capitalize">{title}</h1>
</Gradient>

// app/blocks/gradient-hero.block.tsx
import clsx from 'clsx'
import { Gradient } from '~/components/gradient'

export interface GradientHeroBlockProps {
  title: string
}
export function GradientHeroBlock({ title }: GradientHeroBlockProps) {
  return (
    <Gradient
      className={clsx([
        'no-prose relative header-offset-mobile lg:header-offset-desktop',
        'flex justify-center items-end min-h-[30vh]',
      ])}
    >
      <h1 className="my-16 capitalize heading-1">{title}</h1>
    </Gradient>
  )
}
