// components/more-button.tsx
import Link from 'next/link'
import clsx from 'clsx'
import { RightArrowIcon } from './icons'

export interface MoreButtonProps {
  href: string
  title: string
  className?: string
}
export function MoreButton({ href, title, className }: MoreButtonProps) {
  return (
    <Link className={clsx('flex gap-2 items-center hover:text-accent', className)} href={href}>
      <span className="text-sm font-medium uppercase font-heading">{title}</span>
      <RightArrowIcon className="w-5 h-5 p-1 bg-white border border-current rounded-full bg-opacity-90" />
    </Link>
  )
}

// src/lib/components/MoreButton.svelte
<script lang="ts">
	import RightArrowIcon from './icons/RightArrowIcon.svelte'

	export let href: string
	export let title: string
</script>

<a class="flex items-center gap-2 hover:text-accent {$$props.class ?? ''}" {href}>
	<span class="font-heading text-sm font-medium uppercase">{title}</span>
	<RightArrowIcon class="h-5 w-5 rounded-full border border-current bg-white bg-opacity-90 p-1" />
</a>
